### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by lucaspeferreira** [lucaspeferreira/rfid-nefro#6]
- [ ] Instalar o MicroPython na ESP32
- [ ] Tornar funcional o sensor de RFID 
- [ ] Tornar funcional o indicador utilizando o LED
- [ ] Tornar funcional o alto falante
- [ ] Exibir no painel a informação referente ao RFID lido
- [ ]
